apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: dot-api
spec:
  environments:
    - name: prod
    - name: test
      build:
        from: v0*
    - name: dev
      build:
        from: main|dev-deploy*
  components:
    - name: api
      src: .
      dockerfile: .
      ports:
        - name: http
          port: 8000
      publicPort: http
      secrets:
        - CLIENT_SECRET
      resources:
        requests:
          memory: '900Mi'
          cpu: '40m'
        limits:
          memory: '1000Mi'
          cpu: '60m'
        horizontalScaling:
          resources:
            memory:
              averageUtilization: 75
            cpu:
              averageUtilization: 85
          minReplicas: 1
          maxReplicas: 3
      environmentConfig:

        - environment: prod
          replicas: 1
          variables:
            CLIENT_ID: '4251833c-b9c3-4013-afda-cbfd2cc50f3f'
            REDIRECT_URL: 'https://api-dot-api-prod.radix.equinor.com/docs/oauth2-redirect'
            AUDIENCE: "4251833c-b9c3-4013-afda-cbfd2cc50f3f"
            SCOPE: '4251833c-b9c3-4013-afda-cbfd2cc50f3f/Read'
            APP_ENV: 'production'
            DATABASE_CONN_PROD: 'DRIVER={ODBC Driver 18 for SQL Server};Server=decision-optimization-sqlserver-prod.database.windows.net;Database=decision-optimization-sqldb-prod;'
          azure:
              clientId: c0d1f6a5-93b5-432b-8c2e-bf26583a7626
        - environment: test
          replicas: 1
          variables:
            CLIENT_ID: '945882c1-69f4-41cd-a42a-22516ca01868'
            REDIRECT_URL: 'https://api-dot-api-test.radix.equinor.com/docs/oauth2-redirect'
            AUDIENCE: "945882c1-69f4-41cd-a42a-22516ca01868"
            APP_ENV: 'test'
            SCOPE: '945882c1-69f4-41cd-a42a-22516ca01868/Read'
            DATABASE_CONN_TEST: 'DRIVER={ODBC Driver 18 for SQL Server};Server=decision-optimization-sqlserver-test.database.windows.net;Database=decision-optimization-sqldb-test;'
          identity:
            azure:
              clientId: c0d1f6a5-93b5-432b-8c2e-bf26583a7626
        - environment: dev  
          replicas: 1
          variables:
            CLIENT_ID: '4251833c-b9c3-4013-afda-cbfd2cc50f3f'
            REDIRECT_URL: 'https://api-dot-api-dev.radix.equinor.com/docs/oauth2-redirect'
            AUDIENCE: "4251833c-b9c3-4013-afda-cbfd2cc50f3f"
            APP_ENV: 'dev'
            DATABASE_CONN_DEV: 'DRIVER={ODBC Driver 18 for SQL Server};Server=decision-optimization-sqlserver-dev.database.windows.net;Database=decision-optimization-sqldb-dev;'
            SCOPE: '4251833c-b9c3-4013-afda-cbfd2cc50f3f/Read'
          identity:
            azure:
              clientId: c0d1f6a5-93b5-432b-8c2e-bf26583a7626