"""changed project description to opportunity statement

Revision ID: 0fd01ae4d4fe
Revises: db0f6ffedd37
Create Date: 2025-10-22 09:25:22.027824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fd01ae4d4fe'
down_revision: Union[str, None] = 'db0f6ffedd37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('opportunityStatement', sa.String(length=600), nullable=False, server_default=''))
    op.drop_column('project', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('description', sa.VARCHAR(length=600, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.drop_column('project', 'opportunityStatement')
    # ### end Alembic commands ###
