"""add project end date

Revision ID: 15e8a840c448
Revises: fae2f9a90fcf
Create Date: 2025-10-06 12:06:21.822183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e8a840c448'
down_revision: Union[str, None] = 'fae2f9a90fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('public', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column(
        'project',
        sa.Column(
            'end_date',
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("DATEADD(month, 1, CURRENT_TIMESTAMP)")
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'end_date')
    op.drop_column('project', 'public')
    # ### end Alembic commands ###
