"""set index in project role table

Revision ID: 21334adf266d
Revises: a412de1391bf
Create Date: 2025-08-21 15:00:49.708064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.models.guid import GUID


# revision identifiers, used by Alembic.
revision: str = '21334adf266d'
down_revision: Union[str, None] = 'a412de1391bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_role', sa.Column('id', GUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_role', 'id')
    # ### end Alembic commands ###
