"""remove opport name

Revision ID: 234ed875bf40
Revises: 589643041c80
Create Date: 2025-10-02 10:33:51.444323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234ed875bf40'
down_revision: Union[str, None] = '589643041c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_name'), table_name='opportunity')
    op.drop_column('opportunity', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity', sa.Column('name', sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_opportunity_name'), 'opportunity', ['name'], unique=False)
    # ### end Alembic commands ###
