"""base enity dates to utc

Revision ID: 276dbba9f2b1
Revises: 0fd01ae4d4fe
Create Date: 2025-10-27 12:12:36.123566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276dbba9f2b1'
down_revision: Union[str, None] = '0fd01ae4d4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('decision', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('decision', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('edge', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('edge', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('issue', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('issue', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('node', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('node', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('node_style', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('node_style', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('objective', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('objective', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('opportunity', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('opportunity', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('option', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('option', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('outcome', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('outcome', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('project', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('project', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('project_role', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('project_role', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('scenario', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('scenario', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('uncertainty', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('uncertainty', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('user', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('user', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('utility', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('utility', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('value_metric', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('value_metric', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('value_metric', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('value_metric', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('utility', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('utility', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('user', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('uncertainty', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('uncertainty', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('scenario', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.alter_column('scenario', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.alter_column('project_role', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.alter_column('project_role', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.alter_column('project', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.alter_column('project', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.alter_column('outcome', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.alter_column('outcome', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.alter_column('option', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.alter_column('option', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.alter_column('opportunity', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.alter_column('opportunity', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.alter_column('objective', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.alter_column('objective', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.alter_column('node_style', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('node_style', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('node', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('node', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('issue', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.alter_column('issue', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.alter_column('edge', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('edge', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('decision', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('decision', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))
    # ### end Alembic commands ###
