"""add edge to probs

Revision ID: 2f4f27b9575c
Revises: 60779826473d
Create Date: 2025-10-29 08:21:36.827967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.models.guid import GUID

# revision identifiers, used by Alembic.
revision: str = '2f4f27b9575c'
down_revision: Union[str, None] = '60779826473d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discrete_probability_parent_option', sa.Column('edge_id', GUID(), nullable=False))
    op.create_foreign_key(None, 'discrete_probability_parent_option', 'edge', ['edge_id'], ['id'])
    op.add_column('discrete_probability_parent_outcome', sa.Column('edge_id', GUID(), nullable=False))
    op.create_foreign_key(None, 'discrete_probability_parent_outcome', 'edge', ['edge_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discrete_probability_parent_outcome', type_='foreignkey')
    op.drop_column('discrete_probability_parent_outcome', 'edge_id')
    op.drop_constraint(None, 'discrete_probability_parent_option', type_='foreignkey')
    op.drop_column('discrete_probability_parent_option', 'edge_id')
    # ### end Alembic commands ###
