"""add is default

Revision ID: 355ec823911a
Revises: 52e8822ba450
Create Date: 2025-08-29 08:04:30.341581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '355ec823911a'
down_revision: Union[str, None] = '52e8822ba450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario', 'is_default')
    # ### end Alembic commands ###