"""probability relational fixes

Revision ID: 3c7bff90226a
Revises: 60779826473d
Create Date: 2025-11-10 08:59:19.257955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c7bff90226a'
down_revision: Union[str, None] = '60779826473d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FK__discrete___child__09A971A2'), 'discrete_probability', type_='foreignkey')
    op.create_foreign_key(None, 'discrete_probability', 'outcome', ['child_outcome_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('FK__discrete___paren__0E6E26BF'), 'discrete_probability_parent_option', type_='foreignkey')
    op.create_foreign_key(None, 'discrete_probability_parent_option', 'option', ['parent_option_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('FK__discrete___paren__123EB7A3'), 'discrete_probability_parent_outcome', type_='foreignkey')
    op.create_foreign_key(None, 'discrete_probability_parent_outcome', 'outcome', ['parent_outcome_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discrete_probability_parent_outcome', type_='foreignkey')
    op.create_foreign_key(op.f('FK__discrete___paren__123EB7A3'), 'discrete_probability_parent_outcome', 'outcome', ['parent_outcome_id'], ['id'])
    op.drop_constraint(None, 'discrete_probability_parent_option', type_='foreignkey')
    op.create_foreign_key(op.f('FK__discrete___paren__0E6E26BF'), 'discrete_probability_parent_option', 'option', ['parent_option_id'], ['id'])
    op.drop_constraint(None, 'discrete_probability', type_='foreignkey')
    op.create_foreign_key(op.f('FK__discrete___child__09A971A2'), 'discrete_probability', 'outcome', ['child_outcome_id'], ['id'])
    # ### end Alembic commands ###
