"""Added height and width in nodestyle

Revision ID: 4fcae4b62683
Revises: e915e38cedc2
Create Date: 2025-10-17 12:55:10.801087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fcae4b62683'
down_revision: Union[str, None] = 'e915e38cedc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_style', sa.Column('width', sa.INTEGER(), nullable=False,server_default=sa.text('200')))
    op.add_column('node_style', sa.Column('height', sa.INTEGER(), nullable=False,server_default=sa.text('150')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node_style', 'height')
    op.drop_column('node_style', 'width')
    # ### end Alembic commands ###
