"""Added index in foreign key

Revision ID: 52ad96deb7bc
Revises: fae2f9a90fcf
Create Date: 2025-10-08 11:22:15.852186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ad96deb7bc'
down_revision: Union[str, None] = 'fae2f9a90fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_decision_issue_id'), 'decision', ['issue_id'], unique=False)
    op.create_index(op.f('ix_edge_head_id'), 'edge', ['head_id'], unique=False)
    op.create_index(op.f('ix_edge_scenario_id'), 'edge', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_edge_tail_id'), 'edge', ['tail_id'], unique=False)
    op.create_index(op.f('ix_node_issue_id'), 'node', ['issue_id'], unique=False)
    op.create_index(op.f('ix_node_scenario_id'), 'node', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_node_style_node_id'), 'node_style', ['node_id'], unique=False)
    op.create_index(op.f('ix_option_decision_id'), 'option', ['decision_id'], unique=False)
    op.create_index(op.f('ix_outcome_uncertainty_id'), 'outcome', ['uncertainty_id'], unique=False)
    op.create_index(op.f('ix_uncertainty_issue_id'), 'uncertainty', ['issue_id'], unique=False)
    op.create_index(op.f('ix_utility_issue_id'), 'utility', ['issue_id'], unique=False)
    op.create_index(op.f('ix_value_metric_issue_id'), 'value_metric', ['issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_value_metric_issue_id'), table_name='value_metric')
    op.drop_index(op.f('ix_utility_issue_id'), table_name='utility')
    op.drop_index(op.f('ix_uncertainty_issue_id'), table_name='uncertainty')
    op.drop_index(op.f('ix_outcome_uncertainty_id'), table_name='outcome')
    op.drop_index(op.f('ix_option_decision_id'), table_name='option')
    op.drop_index(op.f('ix_node_style_node_id'), table_name='node_style')
    op.drop_index(op.f('ix_node_scenario_id'), table_name='node')
    op.drop_index(op.f('ix_node_issue_id'), table_name='node')
    op.drop_index(op.f('ix_edge_tail_id'), table_name='edge')
    op.drop_index(op.f('ix_edge_scenario_id'), table_name='edge')
    op.drop_index(op.f('ix_edge_head_id'), table_name='edge')
    op.drop_index(op.f('ix_decision_issue_id'), table_name='decision')
    # ### end Alembic commands ###
