"""Remove project owner and project contributor table

Revision ID: 52e8822ba450
Revises: 7fc502c4a110
Create Date: 2025-08-27 08:35:40.992898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = "52e8822ba450"
down_revision: Union[str, None] = "7fc502c4a110"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_owners")
    op.drop_table("project_contributors")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_contributors",
        sa.Column("project_id", mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("created_at", sa.DATETIME(), autoincrement=False, nullable=False),
        sa.Column("updated_at", sa.DATETIME(), autoincrement=False, nullable=False),
        sa.Column("created_by_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("updated_by_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["user.id"], name=op.f("FK__project_c__creat__3864608B")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.id"], name=op.f("FK__project_c__proje__395884C4")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"], ["user.id"], name=op.f("FK__project_c__updat__3A4CA8FD")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("FK__project_c__user___3B40CD36")
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "user_id", name=op.f("PK__project___57E27D6F1A741007")
        ),
    )
    op.create_table(
        "project_owners",
        sa.Column("project_id", mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("created_at", sa.DATETIME(), autoincrement=False, nullable=False),
        sa.Column("updated_at", sa.DATETIME(), autoincrement=False, nullable=False),
        sa.Column("created_by_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("updated_by_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["user.id"], name=op.f("FK__project_o__creat__3E1D39E1")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.id"], name=op.f("FK__project_o__proje__3F115E1A")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"], ["user.id"], name=op.f("FK__project_o__updat__40058253")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("FK__project_o__user___40F9A68C")
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "user_id", name=op.f("PK__project___57E27D6F8C020909")
        ),
    )
    # ### end Alembic commands ###
