"""add edge to probs

Revision ID: 62c8507a6643
Revises: 60779826473d
Create Date: 2025-10-29 13:37:57.020648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.models.guid import GUID

# revision identifiers, used by Alembic.
revision: str = '62c8507a6643'
down_revision: Union[str, None] = '60779826473d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discrete_probability_parent_option', sa.Column('edge_id', GUID(), nullable=False))
    op.drop_constraint(op.f('FK__discrete___paren__0E6E26BF'), 'discrete_probability_parent_option', type_='foreignkey')
    op.drop_constraint(op.f('FK__discrete___discr__0D7A0286'), 'discrete_probability_parent_option', type_='foreignkey')
    op.create_foreign_key('fk_discrete_prob_parent_option_discrete_probability', 'discrete_probability_parent_option', 'discrete_probability', ['discrete_probability_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_discrete_prob_parent_option_option', 'discrete_probability_parent_option', 'option', ['parent_option_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_discrete_prob_parent_option_edge', 'discrete_probability_parent_option', 'edge', ['edge_id'], ['id'], ondelete='CASCADE')
    op.add_column('discrete_probability_parent_outcome', sa.Column('edge_id', GUID(), nullable=True))
    op.create_index(op.f('ix_discrete_probability_parent_outcome_edge_id'), 'discrete_probability_parent_outcome', ['edge_id'], unique=False)
    op.drop_constraint(op.f('FK__discrete___paren__123EB7A3'), 'discrete_probability_parent_outcome', type_='foreignkey')
    op.drop_constraint(op.f('FK__discrete___discr__114A936A'), 'discrete_probability_parent_outcome', type_='foreignkey')
    op.create_foreign_key('fk_discrete_prob_parent_outcome_outcome', 'discrete_probability_parent_outcome', 'outcome', ['parent_outcome_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_discrete_prob_parent_outcome_edge', 'discrete_probability_parent_outcome', 'edge', ['edge_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_discrete_prob_parent_outcome_discrete_probability', 'discrete_probability_parent_outcome', 'discrete_probability', ['discrete_probability_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_discrete_prob_parent_outcome_discrete_probability', 'discrete_probability_parent_outcome', type_='foreignkey')
    op.drop_constraint('fk_discrete_prob_parent_outcome_edge', 'discrete_probability_parent_outcome', type_='foreignkey')
    op.drop_constraint('fk_discrete_prob_parent_outcome_outcome', 'discrete_probability_parent_outcome', type_='foreignkey')
    op.create_foreign_key(op.f('FK__discrete___discr__114A936A'), 'discrete_probability_parent_outcome', 'discrete_probability', ['discrete_probability_id'], ['id'])
    op.create_foreign_key(op.f('FK__discrete___paren__123EB7A3'), 'discrete_probability_parent_outcome', 'outcome', ['parent_outcome_id'], ['id'])
    op.drop_index(op.f('ix_discrete_probability_parent_outcome_edge_id'), table_name='discrete_probability_parent_outcome')
    op.drop_column('discrete_probability_parent_outcome', 'edge_id')
    op.drop_constraint('fk_discrete_prob_parent_option_edge', 'discrete_probability_parent_option', type_='foreignkey')
    op.drop_constraint('fk_discrete_prob_parent_option_option', 'discrete_probability_parent_option', type_='foreignkey')
    op.drop_constraint('fk_discrete_prob_parent_option_discrete_probability', 'discrete_probability_parent_option', type_='foreignkey')
    op.create_foreign_key(op.f('FK__discrete___discr__0D7A0286'), 'discrete_probability_parent_option', 'discrete_probability', ['discrete_probability_id'], ['id'])
    op.create_foreign_key(op.f('FK__discrete___paren__0E6E26BF'), 'discrete_probability_parent_option', 'option', ['parent_option_id'], ['id'])
    op.drop_column('discrete_probability_parent_option', 'edge_id')
    # ### end Alembic commands ###
