"""Add options and outcomes

Revision ID: 7fc502c4a110
Revises: 41df6b43c1a3
Create Date: 2025-08-19 09:25:53.065989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.models.guid import GUID


# revision identifiers, used by Alembic.
revision: str = "7fc502c4a110"
down_revision: Union[str, None] = "41df6b43c1a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "option",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("decision_id", GUID(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("utility", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decision.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "outcome",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("uncertainty_id", GUID(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("utility", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["uncertainty_id"],
            ["uncertainty.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("decision", "alternatives")
    op.create_index(op.f("ix_issue_scenario_id"), "issue", ["scenario_id"], unique=False)
    op.drop_column("uncertainty", "probabilities")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "uncertainty",
        sa.Column(
            "probabilities",
            sa.VARCHAR(collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_issue_scenario_id"), table_name="issue")
    op.add_column(
        "decision",
        sa.Column(
            "alternatives",
            sa.VARCHAR(length=60, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("outcome")
    op.drop_table("option")
    # ### end Alembic commands ###
