"""rename child outcome

Revision ID: 801e6553b08a
Revises: 9f2d4447120d
Create Date: 2025-12-03 10:40:04.019985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
from src.models.guid import GUID
# revision identifiers, used by Alembic.
revision: str = '801e6553b08a'
down_revision: Union[str, None] = '9f2d4447120d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add new column as nullable
    op.add_column('discrete_probability', sa.Column('outcome_id', GUID(), nullable=True))
    
    # Step 2: Copy data from old column to new column
    op.execute('UPDATE discrete_probability SET outcome_id = child_outcome_id')
    
    # Step 3: Make new column NOT NULL
    op.alter_column('discrete_probability', 'outcome_id', existing_type=GUID(), nullable=False)
    
    # Step 4: Drop old foreign key and index
    op.drop_constraint(op.f('FK__discrete___child__6FE99F9F'), 'discrete_probability', type_='foreignkey')
    op.drop_index(op.f('ix_discrete_probability_child_outcome_id'), table_name='discrete_probability')
    
    # Step 5: Create new index and foreign key
    op.create_index(op.f('ix_discrete_probability_outcome_id'), 'discrete_probability', ['outcome_id'], unique=False)
    op.create_foreign_key('FK__discrete___outcome__6FE99F9F', 'discrete_probability', 'outcome', ['outcome_id'], ['id'], ondelete='CASCADE')
    
    # Step 6: Drop old column
    op.drop_column('discrete_probability', 'child_outcome_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add old column as nullable
    op.add_column('discrete_probability', sa.Column('child_outcome_id', GUID(), autoincrement=False, nullable=True))
    
    # Step 2: Copy data from new column to old column
    op.execute('UPDATE discrete_probability SET child_outcome_id = outcome_id')
    
    # Step 3: Make old column NOT NULL
    op.alter_column('discrete_probability', 'child_outcome_id', existing_type=GUID(), nullable=False)
    
    # Step 4: Drop new foreign key and index
    op.drop_constraint('FK__discrete___outcome__6FE99F9F', 'discrete_probability', type_='foreignkey')
    op.drop_index(op.f('ix_discrete_probability_outcome_id'), table_name='discrete_probability')
    
    # Step 5: Create old index and foreign key
    op.create_foreign_key(op.f('FK__discrete___child__6FE99F9F'), 'discrete_probability', 'outcome', ['child_outcome_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_discrete_probability_child_outcome_id'), 'discrete_probability', ['child_outcome_id'], unique=False)
    
    # Step 6: Drop new column
    op.drop_column('discrete_probability', 'outcome_id')
    # ### end Alembic commands ###
