"""add project end date

Revision ID: 8312080f10f9
Revises: 589643041c80
Create Date: 2025-10-02 11:15:06.787524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8312080f10f9'
down_revision: Union[str, None] = '589643041c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('public', sa.Boolean(), nullable=False))
    op.add_column('project', sa.Column('end_date', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'end_date')
    op.drop_column('project', 'public')
    # ### end Alembic commands ###
