"""probability relational fixes

Revision ID: 84ee713797e0
Revises: 60779826473d
Create Date: 2025-11-11 08:40:50.119423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ee713797e0'
down_revision: Union[str, None] = '60779826473d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discrete_probability', 'probability',
               existing_type=sa.FLOAT(precision=53),
               type_=sa.Float(precision=14),
               nullable=True)
    op.drop_constraint(op.f('FK__discrete___child__09A971A2'), 'discrete_probability', type_='foreignkey')
    op.create_foreign_key('FK__discrete___child__09A971A2', 'discrete_probability', 'outcome', ['child_outcome_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('FK__discrete___paren__0E6E26BF'), 'discrete_probability_parent_option', type_='foreignkey')
    op.create_foreign_key('FK__discrete___paren__0E6E26BF', 'discrete_probability_parent_option', 'option', ['parent_option_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('FK__discrete___paren__123EB7A3'), 'discrete_probability_parent_outcome', type_='foreignkey')
    op.create_foreign_key('FK__discrete___paren__123EB7A3', 'discrete_probability_parent_outcome', 'outcome', ['parent_outcome_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK__discrete___paren__123EB7A3', 'discrete_probability_parent_outcome', type_='foreignkey')
    op.create_foreign_key(op.f('FK__discrete___paren__123EB7A3'), 'discrete_probability_parent_outcome', 'outcome', ['parent_outcome_id'], ['id'])
    op.drop_constraint('FK__discrete___paren__0E6E26BF', 'discrete_probability_parent_option', type_='foreignkey')
    op.create_foreign_key(op.f('FK__discrete___paren__0E6E26BF'), 'discrete_probability_parent_option', 'option', ['parent_option_id'], ['id'])
    op.drop_constraint('FK__discrete___child__09A971A2', 'discrete_probability', type_='foreignkey')
    op.create_foreign_key(op.f('FK__discrete___child__09A971A2'), 'discrete_probability', 'outcome', ['child_outcome_id'], ['id'])
    op.alter_column('discrete_probability', 'probability',
               existing_type=sa.Float(precision=14),
               type_=sa.FLOAT(precision=53),
               nullable=False)
    # ### end Alembic commands ###
