"""Add date audit on all models

Revision ID: 8ae59d10edd3
Revises: 7da9a48474d5
Create Date: 2025-08-05 08:46:35.687672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision: str = "8ae59d10edd3"
down_revision: Union[str, None] = "7da9a48474d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "decision",
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=func.now()),
    )
    op.add_column(
        "decision",
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=func.now()),
    )
    op.add_column(
        "edge", sa.Column("created_at", sa.DateTime(), nullable=False, server_default=func.now())
    )
    op.add_column(
        "edge", sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=func.now())
    )
    op.add_column(
        "node", sa.Column("created_at", sa.DateTime(), nullable=False, server_default=func.now())
    )
    op.add_column(
        "node", sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=func.now())
    )
    op.add_column(
        "node_style",
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=func.now()),
    )
    op.add_column(
        "node_style",
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=func.now()),
    )
    op.add_column(
        "uncertainty",
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=func.now()),
    )
    op.add_column(
        "uncertainty",
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=func.now()),
    )
    op.add_column(
        "user", sa.Column("created_at", sa.DateTime(), nullable=False, server_default=func.now())
    )
    op.add_column(
        "user", sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=func.now())
    )
    op.add_column(
        "utility", sa.Column("created_at", sa.DateTime(), nullable=False, server_default=func.now())
    )
    op.add_column(
        "utility", sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=func.now())
    )
    op.add_column(
        "value_metric",
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=func.now()),
    )
    op.add_column(
        "value_metric",
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=func.now()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("value_metric", "updated_at")
    op.drop_column("value_metric", "created_at")
    op.drop_column("utility", "updated_at")
    op.drop_column("utility", "created_at")
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_column("uncertainty", "updated_at")
    op.drop_column("uncertainty", "created_at")
    op.drop_column("node_style", "updated_at")
    op.drop_column("node_style", "created_at")
    op.drop_column("node", "updated_at")
    op.drop_column("node", "created_at")
    op.drop_column("edge", "updated_at")
    op.drop_column("edge", "created_at")
    op.drop_column("decision", "updated_at")
    op.drop_column("decision", "created_at")
    # ### end Alembic commands ###
