"""added project role table

Revision ID: a412de1391bf
Revises: 7fc502c4a110
Create Date: 2025-08-20 14:05:12.723514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

from src.models.guid import GUID

# revision identifiers, used by Alembic.
revision: str = 'a412de1391bf'
down_revision: Union[str, None] = '7fc502c4a110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_role',
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.drop_table('project_contributors')
    op.drop_table('project_owners')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_owners',
    sa.Column('project_id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('FK__project_o__creat__3E1D39E1')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('FK__project_o__proje__3F115E1A')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('FK__project_o__updat__40058253')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('FK__project_o__user___40F9A68C')),
    sa.PrimaryKeyConstraint('project_id', 'user_id', name=op.f('PK__project___57E27D6F8C020909'))
    )
    op.create_table('project_contributors',
    sa.Column('project_id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('FK__project_c__creat__3864608B')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('FK__project_c__proje__395884C4')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('FK__project_c__updat__3A4CA8FD')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('FK__project_c__user___3B40CD36')),
    sa.PrimaryKeyConstraint('project_id', 'user_id', name=op.f('PK__project___57E27D6F1A741007'))
    )
    op.drop_table('project_role')
    # ### end Alembic commands ###
