"""node style refactor

Revision ID: c9f840341a96
Revises: e36ea2b1d4e4
Create Date: 2025-11-10 11:06:04.227689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f840341a96'
down_revision: Union[str, None] = 'e36ea2b1d4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('node_style', 'x_position',
               existing_type=sa.INTEGER(),
               type_=sa.FLOAT(precision=14),
               existing_nullable=False)
    op.alter_column('node_style', 'y_position',
               existing_type=sa.INTEGER(),
               type_=sa.FLOAT(precision=14),
               existing_nullable=False)
    op.drop_column('node_style', 'height')
    op.drop_column('node_style', 'width')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_style', sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('node_style', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('node_style', 'y_position',
               existing_type=sa.FLOAT(precision=14),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('node_style', 'x_position',
               existing_type=sa.FLOAT(precision=14),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
