"""is_key_and_decision_type

Revision ID: db0f6ffedd37
Revises: 4fcae4b62683
Create Date: 2025-10-21 10:56:20.466941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db0f6ffedd37'
down_revision: Union[str, None] = '4fcae4b62683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision', sa.Column('type', sa.String(length=60), nullable=False, server_default="Focus"))
    op.add_column('uncertainty', sa.Column('is_key', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uncertainty', 'is_key')
    op.drop_column('decision', 'type')
    # ### end Alembic commands ###
