"""conditional_probabilities

Revision ID: ec2aad9de30f
Revises: c9f840341a96
Create Date: 2025-12-04 10:00:11.381755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
from src.models.guid import GUID

# revision identifiers, used by Alembic.
revision: str = 'ec2aad9de30f'
down_revision: Union[str, None] = 'c9f840341a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discrete_probability',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('outcome_id', GUID(), nullable=False),
    sa.Column('uncertainty_id', GUID(), nullable=False),
    sa.Column('probability', sa.Float(precision=14), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uncertainty_id'], ['uncertainty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discrete_probability_outcome_id'), 'discrete_probability', ['outcome_id'], unique=False)
    op.create_index(op.f('ix_discrete_probability_uncertainty_id'), 'discrete_probability', ['uncertainty_id'], unique=False)
    op.create_table('discrete_probability_parent_option',
    sa.Column('discrete_probability_id', GUID(), nullable=False),
    sa.Column('parent_option_id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['discrete_probability_id'], ['discrete_probability.id'], ),
    sa.ForeignKeyConstraint(['parent_option_id'], ['option.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('discrete_probability_id', 'parent_option_id')
    )
    op.create_table('discrete_probability_parent_outcome',
    sa.Column('discrete_probability_id', GUID(), nullable=False),
    sa.Column('parent_outcome_id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['discrete_probability_id'], ['discrete_probability.id'], ),
    sa.ForeignKeyConstraint(['parent_outcome_id'], ['outcome.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('discrete_probability_id', 'parent_outcome_id')
    )
    op.alter_column('node_style', 'x_position',
               existing_type=mssql.REAL(),
               type_=sa.FLOAT(precision=14),
               existing_nullable=False)
    op.alter_column('node_style', 'y_position',
               existing_type=mssql.REAL(),
               type_=sa.FLOAT(precision=14),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('node_style', 'y_position',
               existing_type=sa.FLOAT(precision=14),
               type_=mssql.REAL(),
               existing_nullable=False)
    op.alter_column('node_style', 'x_position',
               existing_type=sa.FLOAT(precision=14),
               type_=mssql.REAL(),
               existing_nullable=False)
    op.drop_table('discrete_probability_parent_outcome')
    op.drop_table('discrete_probability_parent_option')
    op.drop_index(op.f('ix_discrete_probability_uncertainty_id'), table_name='discrete_probability')
    op.drop_index(op.f('ix_discrete_probability_outcome_id'), table_name='discrete_probability')
    op.drop_table('discrete_probability')
    # ### end Alembic commands ###
