"""added_project_role_table

Revision ID: ee08f39e47aa
Revises: 52e8822ba450
Create Date: 2025-09-09 08:45:44.875474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.models.guid import GUID


# revision identifiers, used by Alembic.
revision: str = "ee08f39e47aa"
down_revision: Union[str, None] = "52e8822ba450"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_role",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("project_id", GUID(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=60), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("updated_by_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_role_project_id"), "project_role", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_project_role_user_id"), "project_role", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_role_user_id"), table_name="project_role")
    op.drop_index(op.f("ix_project_role_project_id"), table_name="project_role")
    op.drop_table("project_role")
    # ### end Alembic commands ###
