"""add objective type

Revision ID: fae2f9a90fcf
Revises: 234ed875bf40
Create Date: 2025-10-03 07:47:30.131542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae2f9a90fcf'
down_revision: Union[str, None] = '234ed875bf40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objective', sa.Column('type', sa.String(length=60), nullable=False, server_default="Strategic"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objective', 'type')
    # ### end Alembic commands ###
