name: Pass tests before merge to main branch

on:
  push:
    tags:
      - "v*"
jobs:
  run-pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Run migration
        env:
          APP_ENV: test
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: alembic upgrade head
